### ISSUE TITLE
Action Fails to Run

### ISSUE THREAD

**Issue by cgspeck** [AppImageCrafters/build-appimage-action#1]
This action fails to run with the following error during the setup phase of the job:

```
Download action repository 'AppImageCrafters/build-appimage-action@master'
Error: 'appimagecrafters/appimage-builder:0.8.2' should be either '[path]/Dockerfile' or 'docker://image[:tag]'.
```

The relevant snippet of [my build](https://github.com/cgspeck/brewtarget/blob/4a53a252c10c96c531a13ae63c87f7ae9bf80289/.github/workflows/linux-ubuntu.yml#L64) is here:
```
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage-action@master
        env:
          UPDATE_INFO: gh-releases-zsync|cgspeck|brewtarget|latest|*x86_64.AppImage.zsync
        with:
          recipe: build-scripts/linux/AppImageBuilder.yml
```
