### ISSUE TITLE
GitHub Action is limited to 1 input argument

### ISSUE THREAD

**Issue by git-developer** [AppImageCrafters/build-appimage-action#7]
### Problem
The GitHub Action is limited to a single input argument.

### Cause
Currently, [action.yml](https://github.com/AppImageCrafters/build-appimage/blob/57c3bc6963f870ce3be103117de5b5e33ffbaeb6/action.yml#L18C1-L21C27) looks like this:
```yaml
  args:
    - appimage-builder
    - '--recipe=${{ inputs.recipe }}' 
    - '${{ inputs.args }}'
```

`inputs.args` is not a list, but a single string. Thus it is not possible to use more than one argument. Example:
```yaml
  uses: AppImageCrafters/build-appimage@v1.3
  with:
    recipe: dist/AppImageBuilder.yml
    args: --skip-tests --appdir "Custom AppDir"
```

This will run the appimage-builder container with 3 arguments:
- `appimage-builder`
- `--recipe=dist/AppImageBuilder.yml`
- `--skip-tests --appdir "Custom AppDir"`

The container run fails because it the input args are merged into one big string:
```
/usr/bin/docker run [...] appimagecrafters/appimage-builder:1.1.0  "appimage-builder" "--recipe=dist/AppImageBuilder.yml" "--appdir \"CustomAppDir\" --skip-tests"
usage: appimage-builder [-h] [-v] [--recipe RECIPE] [--build-dir BUILD_DIR]
                        [--appdir APPDIR] [--log LOGLEVEL] [--skip-script]
                        [--skip-build] [--skip-tests] [--skip-appimage]
                        [--generate]
appimage-builder: error: unrecognized arguments: "--skip-tests --appdir \"Custom AppDir\""
```

### Possible Solutions
The image must be called using a JSON list instead (see [docs](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsargs)):
```yaml
runs:
  using: 'docker'
  image: docker://appimagecrafters/appimage-builder:1.1.0
  args: [ "appimage-builder", "--recipe=dist/AppImageBuilder.yml", "--skip-tests", "--appdir", "Custom AppDir" ]
```

To do that, `input.args` must be split. There are several possibilities todo that.
#### Newline-separated list
`docker/build-push-action` [uses](https://github.com/docker/build-push-action/blob/0a97817b6ade9f46837855d676c4cca3a2471fc9/src/context.ts#L47) newlines as separator. It would look like
```yaml
- build-args: |
  --skip-tests
  --appdir
  "Custom AppDir"
```
I don't know how to convert this to a JSON list, they use a [library](https://github.com/docker/actions-toolkit/blob/66e22ce5a576b37111879aeed622ebd6fff89881/src/util.ts#L29).

#### JSON list
An alternative is to use the string representation of a JSON list. This would look like:
```yaml
- build-args: '[ "--skip-tests", "--appdir", "Custom AppDir" ]'
```
This string can be converted to a JSON list using the [fromJSON()](https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson) function.

Once the arguments are in JSON list representation, the two args `appimage-builder` and `--recipe=...` have to be added to the head of the list.
